version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - client
      - server
    restart: unless-stopped
    networks:
      - app-network

  server:
    build:
      context: ./SERVER
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URL=mongodb://mongodb:27017/hammasiUy
      - TELEGRAM_BOT_TOKEN=8034976128:AAGuCZJIpqbfQHzGGWBlrvjA5fpJgUX8UKQ
      - CORS_ORIGIN=https://hammasiuy.com
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./SERVER/uploads:/app/uploads

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - MONGO_INITDB_DATABASE=hammasiUy

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
